apiVersion: v1
kind: Secret
metadata:
  name: observer-opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observability-plane.componentLabels" (dict "context" . "component" "observer") | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.observer.openSearch.username | default "admin" | b64enc }}
  password: {{ .Values.observer.openSearch.password | default "ThisIsTheOpenSearchPassword1" | b64enc }}
