apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openchoreo-observability-plane

resources:
  - collector-serviceaccount.yaml
  - collector-clusterrole.yaml
  - collector-clusterrolebinding.yaml
  - collector-configmap.yaml
  - collector-daemonset.yaml
