{{- if .Values.clickstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: clickstack-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observability-plane.componentLabels" (dict "context" . "component" "clickstack") | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.clickstack.credentials.username | default "clickstack_admin" | quote }}
  password: {{ .Values.clickstack.credentials.password | default "ThisIsTheClickStackPassword1" | quote }}
{{- end }}
